### ISSUE TITLE
Error en el encodificado que devuelve el decrypt

### ISSUE THREAD

**Issue by willywg** [augustosamame/culqiruby#4]
Saludos Augusto y gracias por compartir la gema. La estoy usando en un proyecto y tuve un error con el encodificado al enviar un correo de prueba con los parametros desencriptados al finalizar una compra éxitosa. El error en si era: **incompatible character encodings: ASCII-8BIT and UTF-8**

Investigando un poco vi que el encodificado venia de la función que desencripta los textos de Culqi, ya que los devuelve como ASCII-8BIT en vez de UTF-8 como lo sugiere Culqi en su documentación: https://www.culqi.com/docs/#9-4-ejemplo-de-descifrado

> resultado <- Es el valor de “descifrado” codificado en UTF8.

Ya lo estoy por corregir, en breve te mando un pull request

**Comment by augustosamame** [comment]
Fixed in PR https://github.com/augustosamame/culqiruby/pull/5

**Comment by willywg** [comment]
Augusto podrías actualizar la gema para que incluya este cambio?

**Comment by augustosamame** [comment]
Hola William. Incorporé el pull request el 8 de junio: PR https://github.com/augustosamame/culqiruby/pull/5
No tengo ningún otro PR pendiente.

**Comment by willywg** [comment]
@augustosamame creo que estas confundiendo pull request con versiones de la gema en RubyGems. Para hacer uso de los últimos cambios en la gema es necesario volver a subir una versión nueva en RubyGems

**Comment by augustosamame** [comment]
Hola William. Ok, no te había entendido. Ya actualicé la gema, pero si los
cambios son menores, normalmente no actualizaré la gema sino que los
usuarios podrán usar la versión edge desde el master de github. Cuando
acumule varios cambios haré un changelog y actualizaré la gema.

Saludos,
Augusto

2016-06-21 11:32 GMT-05:00 William Wong Garay notifications@github.com:
